# Generated by Django 2.2 on 2020-09-06 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_id', models.IntegerField()),
                ('user_name', models.CharField(max_length=20)),
                ('money', models.IntegerField()),
            ],
        ),
    ]
